spring:
  datasource:
    url: jdbc:mysql://localhost:3306/task?serverTimezone=Asia/Seoul
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    mongodb:
      uri: mongodb://localhost:27017/task
  kafka:
    bootstrap-servers: 192.168.0.203:9092
    consumer:
      auto-offset-reset: latest
      group-id: task
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      properties:
        spring.json.trusted.packages: "*"
      producer:
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


